FROM alpine:3.20@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d

# Install all dependencies
RUN <<EOF
apk update &&
apk upgrade &&
apk add --no-cache bash icu-libs krb5-libs libgcc libintl libssl3 libstdc++ zlib
EOF

# Install .NET runtime
RUN <<EOF
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh &&
chmod +x dotnet-install.sh &&
./dotnet-install.sh --channel 8.0 --version latest --runtime aspnetcore
EOF