# Reference: https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=linux&pivots=dotnet-8-0

# The following Dockerfile is a multi-stage build that builds a .NET 8 application in a container.
# The first stage uses the .NET SDK image to restore, build, and publish the application.
# The second stage uses the .NET runtime image to run the application.
# The final image is smaller because it only contains the published output of the application.

FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:35792ea4ad1db051981f62b313f1be3b46b1f45cadbaa3c288cd0d3056eefb83 AS checkout
WORKDIR /App

# Copy everything
ADD https://github.com/saeedmaghdam/WebSocket.git ./src/

FROM checkout AS restore
WORKDIR /App
# Restore as distinct layers
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore ./src/WebSocketServer/WebSocketServer.csproj

FROM restore AS build-env
# Build
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet build -c Release --no-restore ./src/WebSocketServer/WebSocketServer.csproj

FROM restore AS publish
# Build and publish a release
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet publish -c Release --no-restore -o ./out ./src/WebSocketServer/WebSocketServer.csproj

# Build runtime image
FROM alpine:3.20@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
WORKDIR /App
EXPOSE 80

COPY --from=publish /App/out .

# Install all dependencies
RUN <<EOF
apk update &&
apk upgrade &&
apk add --no-cache bash icu-libs krb5-libs libgcc libintl libssl3 libstdc++ zlib
EOF

# Install .NET runtime
RUN <<EOF
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh &&
chmod +x dotnet-install.sh &&
./dotnet-install.sh --channel 8.0 --version latest --runtime aspnetcore
EOF

ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT [ "/root/.dotnet/dotnet", "WebSocketServer.dll" ]